trigger:
  branches:
    include:
      - main  # Trigger on changes to the 'main' branch

pool:
  name: Default  # Use your self-hosted agent pool

steps:
- script: |
    npm install
    npm run build
    # npm run start
  displayName: 'Deploy Next.js Application on Azure VM'
